### ISSUE TITLE
Is Europe/Germany working?

### ISSUE THREAD

**Issue by philmue1988** [elfive/homebridge-petkit-feeder-mini#17]
Hi, first of all thank you for your plugin. Before I buy the Quantumult X for 9€ I just want to ask is Europe/Germany and also the "Petkit fresh element" is working? Sorry for asking, but I´m not that Pro and I guess I will take some time for me to integrate the plugin, the 2 questions are positiv :)

**Comment by elfive** [comment]
> Hi, first of all thank you for your plugin. Before I buy the Quantumult X for 9€ I just want to ask is Europe/Germany and also the "Petkit fresh element" is working? Sorry for asking, but I´m not that Pro and I guess I will take some time for me to integrate the plugin, the 2 questions are positiv :)

- First, you could use charles(has a free trial) for http netflow capture if you have a PC/Mac, quantumlt X is not necessary, you can find out how to ues charles [there](https://www.charlesproxy.com/).

- Second, if the petkit app works well in Germany, but my plugin not, I can make it work. It's no big deal, you may just submit the http urls.

- Third, currently Petkit fresh element is not tested and may not(very likely) work with my plugin. It's easy if you have one and help me do some simple test(not control your petkit device, but help me capture a http reply data.). For more details, you can goto [this issue](https://github.com/elfive/homebridge-petkit-feeder-mini/issues/15) to find out how to help me add support to you device.
