### ISSUE TITLE
启用插件后会导致Homebridge无法运行

### ISSUE THREAD

**Issue by ariakeumi** [elfive/homebridge-petkit-feeder-mini#20]
日志里没有报错。是Homebridge升级到1.31还是1.32之后才出现的问题，之前使用是正常的。

1. NodeJS version: 14.15.5
2. Homebridge version:1.3.3
3. Plugin version: 1.10.4
4. Example of configure(REMOVE sensitive info!): 
`        {
            "name": "PetkitFeederMini",
            "DropMeal_name": "DropMeal",
            "MealAmount_name": "MealAmount",
            "FoodStorage_name": "FoodStorage",
            "DesiccantLevel_name": "DesiccantLevel",
            "ManualLock_name": "ManualLock",
            "LightMode_name": "LightMode",
            "Battery_name": "Battery",
            "location": "north_america",
            "headers": [
                {
                    "key": "X-Session",
                    "value": "xxxxxx"
                }
            ],
            "autoDeviceInfo": false,
            "sn": "PetkitFeederMini",
            "firmware": "1.0.0",
            "manufacturer": "Petkit",
            "model": "Petkit feeder mini",
            "enable_polling": true,
            "polling_interval": 60,
            "enable_desiccant": false,
            "alert_desiccant_threshold": 7,
            "enable_autoreset_desiccant": false,
            "reset_desiccant_threshold": 5,
            "enable_manualLock": false,
            "enable_lightMode": false,
            "reverse_foodStorage_indicator": false,
            "fast_response": false,
            "accessory": "petkit_feeder_mini"
        }`
5. Logs(REMOVE sensitive info and homebridge debug mode):
`[3/10/2021, 7:16:23 AM] [PetkitFeederMini] Initializing petkit_feeder_mini accessory...
[3/10/2021, 7:16:23 AM] [PetkitFeederMini] begin to initialize petkit feeder mini.
`

**Comment by elfive** [comment]
我测试确实有这个问题，但是似乎这不是我们这个插件的bug，
看起来是一个homebridge的bug，我们正在与homebridge开发者进行沟通，要解决这个问题，可能后期需要我们插件更新适配新版本的Homebridge，但是目前原因不明，所以只能给你一个临时的建议：降级homebridge到v1.2.5版本，而不要去使用v1.3.x版本。

这个Issue请保留直到问题被解决，谢谢。

**Comment by ariakeumi** [comment]
> 我测试确实有这个问题，但是似乎这不是我们这个插件的bug，
> 
> 看起来是一个homebridge的bug，我们正在与homebridge开发者进行沟通，要解决这个问题，可能后期需要我们插件更新适配新版本的Homebridge，但是目前原因不明，所以只能给你一个临时的建议：降级homebridge到v1.2.5版本，而不要去使用v1.3.x版本。
> 
> 
> 
> 这个Issue请保留直到问题被解决，谢谢。

了解！

**Comment by elfive** [comment]
插件v2.0.0版本已经发布，已经解决了导致homebridge卡死的问题。
另外，升级后请务必按照说明修改config.json文件。

**Comment by ariakeumi** [comment]
> 插件v2.0.0版本已经发布，已经解决了导致homebridge卡死的问题。
> 另外，升级后请务必按照说明修改config.json文件。

更新后能正常使用了，赞美作者。

**Comment by elfive** [comment]
如果没有问题了，那么这个issue我就关闭了哦。
